### ISSUE TITLE
Conventional graphql API mapping implementation

### ISSUE THREAD

**Issue by pmi** [enonic/nextjs-adapter#217]
```[tasklist]
### nextjs-demo:
  - [ ] enonic/nextxp-demo#622
  - [ ] enonic/nextxp-demo#635
  - [ ] enonic/nextxp-demo#637
  - [ ] enonic/nextxp-demo#650
  - [ ] enonic/nextxp-demo#652
```

```[tasklist]
### nextjs-adapter:
  - [ ] enonic/nextjs-adapter#218
  - [ ] enonic/nextjs-adapter#248
  - [ ] enonic/nextjs-adapter#255
```

```[tasklist]
### lib-nextxp:
  - [ ] enonic/lib-nextxp#233
  - [ ] enonic/lib-nextxp#239
```

Updated to include @poi33's comment

**Comment by poi33** [comment]
We will also need a configuration in the site.xml / nextxp app to get content studio to request the correct site with the proxy. 

Currently we only specific the href to the next frontend. example: localhost:4242
Content studio needs to request the language specfic site in the proxy too. 

Suggestion we add header data to the request sent to vercel so we we determine on the nextjs side what language of the site we need. Probably append it project repo to the proxy request. (this might be possible to get fro mthe context its requested from in the proxy?)
